# Generated by Django 4.0.4 on 2022-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task1',
            name='dob',
            field=models.DateField(max_length=3),
        ),
    ]
